In [1]:
import numpy as np

In [2]:
dir1 = '/uscms_data/d3/mkim/MKWorkingArea/CMSSW_10_2_0/src/JL/Melrose/P2_CMSSW_10_1_5/src/L1TMuonSimulations/Analyzers/'
infile_muon = dir1 + 'test7/histos_tba.20.npz'
infile_pileup = dir1 + 'test7/histos_tbd.20.npz'
infile_muon_omtf = dir1 + 'test7/histos_tba_omtf.22.npz'
infile_pileup_omtf = dir1 + 'test7/histos_tbd_omtf.22.npz'

In [3]:
loaded = np.load(infile_muon)

In [4]:
the_variables_0 = loaded['variables']

In [ ]:
the_parameters_0 = loaded['parameters']

In [108]:
a = the_variables_0[:10,0:5]
b = the_variables_0[:10,12+0:12+5]

In [109]:
print(a[:10])
print(b[:10])

[[3190.   nan 3546. 3568.   nan]
 [2865.   nan 2622. 2608.   nan]
 [  nan 1415. 1455. 1440. 1408.]
 [3484.   nan 3328. 3328. 3360.]
 [4867.   nan   nan 4648. 4688.]
 [3875.   nan 4008. 4024. 4032.]
 [4308.   nan 3838.   nan   nan]
 [3426.   nan 3720. 3808.   nan]
 [4269.   nan 4022. 3976. 3928.]
 [2096.   nan 1872. 1872. 1910.]]
[[20. nan 17. 16. nan]
 [ 7. nan  6.  6. nan]
 [nan 70. 70. 69. 69.]
 [42. nan 41. 40. 40.]
 [23. nan nan 22. 22.]
 [23. nan 24. 23. 24.]
 [21. nan 18. nan nan]
 [ 9. nan  7.  7. nan]
 [10. nan  9.  8.  8.]
 [34. nan 31. 31. 32.]]


In [123]:
a

array([[3190.,   nan, 3546., 3568.,   nan],
       [2865.,   nan, 2622., 2608.,   nan],
       [  nan, 1415., 1455., 1440., 1408.],
       [3484.,   nan, 3328., 3328., 3360.],
       [4867.,   nan,   nan, 4648., 4688.],
       [3875.,   nan, 4008., 4024., 4032.],
       [4308.,   nan, 3838.,   nan,   nan],
       [3426.,   nan, 3720., 3808.,   nan],
       [4269.,   nan, 4022., 3976., 3928.],
       [2096.,   nan, 1872., 1872., 1910.]], dtype=float32)

In [110]:
a1 = a.reshape((10,5,1))
b1 = b.reshape((10,5,1))

In [91]:
print(a1[:2])

[[[3190.]
  [  nan]
  [3546.]
  [3568.]
  [  nan]]

 [[2865.]
  [  nan]
  [2622.]
  [2608.]
  [  nan]]]


In [121]:
c = np.insert(b1,[0],a1,axis=2)

In [122]:
print(c)

[[[3190.   20.]
  [  nan   nan]
  [3546.   17.]
  [3568.   16.]
  [  nan   nan]]

 [[2865.    7.]
  [  nan   nan]
  [2622.    6.]
  [2608.    6.]
  [  nan   nan]]

 [[  nan   nan]
  [1415.   70.]
  [1455.   70.]
  [1440.   69.]
  [1408.   69.]]

 [[3484.   42.]
  [  nan   nan]
  [3328.   41.]
  [3328.   40.]
  [3360.   40.]]

 [[4867.   23.]
  [  nan   nan]
  [  nan   nan]
  [4648.   22.]
  [4688.   22.]]

 [[3875.   23.]
  [  nan   nan]
  [4008.   24.]
  [4024.   23.]
  [4032.   24.]]

 [[4308.   21.]
  [  nan   nan]
  [3838.   18.]
  [  nan   nan]
  [  nan   nan]]

 [[3426.    9.]
  [  nan   nan]
  [3720.    7.]
  [3808.    7.]
  [  nan   nan]]

 [[4269.   10.]
  [  nan   nan]
  [4022.    9.]
  [3976.    8.]
  [3928.    8.]]

 [[2096.   34.]
  [  nan   nan]
  [1872.   31.]
  [1872.   31.]
  [1910.   32.]]]


In [83]:
print(c)

[[  20.   nan   17.   16.   nan]
 [3190.   nan 3546. 3568.   nan]
 [   7.   nan    6.    6.   nan]
 [2865.   nan 2622. 2608.   nan]
 [  nan   70.   70.   69.   69.]
 [  nan 1415. 1455. 1440. 1408.]
 [  42.   nan   41.   40.   40.]
 [3484.   nan 3328. 3328. 3360.]
 [  23.   nan   nan   22.   22.]
 [4867.   nan   nan 4648. 4688.]
 [  23.   nan   24.   23.   24.]
 [3875.   nan 4008. 4024. 4032.]
 [  21.   nan   18.   nan   nan]
 [4308.   nan 3838.   nan   nan]
 [   9.   nan    7.    7.   nan]
 [3426.   nan 3720. 3808.   nan]
 [  10.   nan    9.    8.    8.]
 [4269.   nan 4022. 3976. 3928.]
 [  34.   nan   31.   31.   32.]
 [2096.   nan 1872. 1872. 1910.]]


In [68]:
print(c)

[[3190.   nan 3546. 3568.   nan   20.   nan   17.   16.   nan]
 [2865.   nan 2622. 2608.   nan    7.   nan    6.    6.   nan]
 [  nan 1415. 1455. 1440. 1408.   nan   70.   70.   69.   69.]
 [3484.   nan 3328. 3328. 3360.   42.   nan   41.   40.   40.]
 [4867.   nan   nan 4648. 4688.   23.   nan   nan   22.   22.]
 [3875.   nan 4008. 4024. 4032.   23.   nan   24.   23.   24.]
 [4308.   nan 3838.   nan   nan   21.   nan   18.   nan   nan]
 [3426.   nan 3720. 3808.   nan    9.   nan    7.    7.   nan]
 [4269.   nan 4022. 3976. 3928.   10.   nan    9.    8.    8.]
 [2096.   nan 1872. 1872. 1910.   34.   nan   31.   31.   32.]]


In [69]:
c.reshape((10,2,5))

array([[[3190.,   nan, 3546., 3568.,   nan],
        [  20.,   nan,   17.,   16.,   nan]],

       [[2865.,   nan, 2622., 2608.,   nan],
        [   7.,   nan,    6.,    6.,   nan]],

       [[  nan, 1415., 1455., 1440., 1408.],
        [  nan,   70.,   70.,   69.,   69.]],

       [[3484.,   nan, 3328., 3328., 3360.],
        [  42.,   nan,   41.,   40.,   40.]],

       [[4867.,   nan,   nan, 4648., 4688.],
        [  23.,   nan,   nan,   22.,   22.]],

       [[3875.,   nan, 4008., 4024., 4032.],
        [  23.,   nan,   24.,   23.,   24.]],

       [[4308.,   nan, 3838.,   nan,   nan],
        [  21.,   nan,   18.,   nan,   nan]],

       [[3426.,   nan, 3720., 3808.,   nan],
        [   9.,   nan,    7.,    7.,   nan]],

       [[4269.,   nan, 4022., 3976., 3928.],
        [  10.,   nan,    9.,    8.,    8.]],

       [[2096.,   nan, 1872., 1872., 1910.],
        [  34.,   nan,   31.,   31.,   32.]]], dtype=float32)

In [66]:
c.reshape((10,5,2))

array([[[3190.,   nan],
        [3546., 3568.],
        [  nan,   20.],
        [  nan,   17.],
        [  16.,   nan]],

       [[2865.,   nan],
        [2622., 2608.],
        [  nan,    7.],
        [  nan,    6.],
        [   6.,   nan]],

       [[  nan, 1415.],
        [1455., 1440.],
        [1408.,   nan],
        [  70.,   70.],
        [  69.,   69.]],

       [[3484.,   nan],
        [3328., 3328.],
        [3360.,   42.],
        [  nan,   41.],
        [  40.,   40.]],

       [[4867.,   nan],
        [  nan, 4648.],
        [4688.,   23.],
        [  nan,   nan],
        [  22.,   22.]],

       [[3875.,   nan],
        [4008., 4024.],
        [4032.,   23.],
        [  nan,   24.],
        [  23.,   24.]],

       [[4308.,   nan],
        [3838.,   nan],
        [  nan,   21.],
        [  nan,   18.],
        [  nan,   nan]],

       [[3426.,   nan],
        [3720., 3808.],
        [  nan,    9.],
        [  nan,    7.],
        [   7.,   nan]],

       [[4269.,   nan],


In [55]:
print(c)

[[[3190.]
  [  nan]
  [3546.]
  [3568.]
  [  nan]
  [  20.]
  [  nan]
  [  17.]
  [  16.]
  [  nan]]

 [[2865.]
  [  nan]
  [2622.]
  [2608.]
  [  nan]
  [   7.]
  [  nan]
  [   6.]
  [   6.]
  [  nan]]

 [[  nan]
  [1415.]
  [1455.]
  [1440.]
  [1408.]
  [  nan]
  [  70.]
  [  70.]
  [  69.]
  [  69.]]

 [[3484.]
  [  nan]
  [3328.]
  [3328.]
  [3360.]
  [  42.]
  [  nan]
  [  41.]
  [  40.]
  [  40.]]

 [[4867.]
  [  nan]
  [  nan]
  [4648.]
  [4688.]
  [  23.]
  [  nan]
  [  nan]
  [  22.]
  [  22.]]

 [[3875.]
  [  nan]
  [4008.]
  [4024.]
  [4032.]
  [  23.]
  [  nan]
  [  24.]
  [  23.]
  [  24.]]

 [[4308.]
  [  nan]
  [3838.]
  [  nan]
  [  nan]
  [  21.]
  [  nan]
  [  18.]
  [  nan]
  [  nan]]

 [[3426.]
  [  nan]
  [3720.]
  [3808.]
  [  nan]
  [   9.]
  [  nan]
  [   7.]
  [   7.]
  [  nan]]

 [[4269.]
  [  nan]
  [4022.]
  [3976.]
  [3928.]
  [  10.]
  [  nan]
  [   9.]
  [   8.]
  [   8.]]

 [[2096.]
  [  nan]
  [1872.]
  [1872.]
  [1910.]
  [  34.]
  [  nan]
  [  31.]
  

In [16]:
#c.reshape((10,5,2))

In [17]:
c.reshape((10,2,5))

array([[[3190.,   nan, 3546., 3568.,   nan],
        [  20.,   nan,   17.,   16.,   nan]],

       [[2865.,   nan, 2622., 2608.,   nan],
        [   7.,   nan,    6.,    6.,   nan]],

       [[  nan, 1415., 1455., 1440., 1408.],
        [  nan,   70.,   70.,   69.,   69.]],

       [[3484.,   nan, 3328., 3328., 3360.],
        [  42.,   nan,   41.,   40.,   40.]],

       [[4867.,   nan,   nan, 4648., 4688.],
        [  23.,   nan,   nan,   22.,   22.]],

       [[3875.,   nan, 4008., 4024., 4032.],
        [  23.,   nan,   24.,   23.,   24.]],

       [[4308.,   nan, 3838.,   nan,   nan],
        [  21.,   nan,   18.,   nan,   nan]],

       [[3426.,   nan, 3720., 3808.,   nan],
        [   9.,   nan,    7.,    7.,   nan]],

       [[4269.,   nan, 4022., 3976., 3928.],
        [  10.,   nan,    9.,    8.,    8.]],

       [[2096.,   nan, 1872., 1872., 1910.],
        [  34.,   nan,   31.,   31.,   32.]]], dtype=float32)

In [27]:
np.transpose(c,[0,1])

array([[3190.,   nan, 3546., 3568.,   nan,   20.,   nan,   17.,   16.,
          nan],
       [2865.,   nan, 2622., 2608.,   nan,    7.,   nan,    6.,    6.,
          nan],
       [  nan, 1415., 1455., 1440., 1408.,   nan,   70.,   70.,   69.,
          69.],
       [3484.,   nan, 3328., 3328., 3360.,   42.,   nan,   41.,   40.,
          40.],
       [4867.,   nan,   nan, 4648., 4688.,   23.,   nan,   nan,   22.,
          22.],
       [3875.,   nan, 4008., 4024., 4032.,   23.,   nan,   24.,   23.,
          24.],
       [4308.,   nan, 3838.,   nan,   nan,   21.,   nan,   18.,   nan,
          nan],
       [3426.,   nan, 3720., 3808.,   nan,    9.,   nan,    7.,    7.,
          nan],
       [4269.,   nan, 4022., 3976., 3928.,   10.,   nan,    9.,    8.,
           8.],
       [2096.,   nan, 1872., 1872., 1910.,   34.,   nan,   31.,   31.,
          32.]], dtype=float32)

In [ ]:
input2_phi = the_variables_0[:,0:5]
input2_theta = the_variables_0[:,12+0:12+5]

In [ ]:
print(np.nanmax(input2_theta))

In [ ]:
input2_phi1 = input2_phi/5000
input2_theta1 = input2_theta/90

In [ ]:
print(input2_phi1[:10])
print(input2_theta1[:10])

In [ ]:
print(np.nanmin(input2_phi1),np.nanmax(input2_phi1))
print(np.nanmin(input2_theta1),np.nanmax(input2_theta1))

In [ ]:
anan = np.array([1,2,np.nan,4,np.nan]) 
bnan = np.array([6,7,np.nan,9,np.nan]) 
hsnan = np.hstack((anan,bnan))

In [ ]:
print(hsnan)

In [ ]:
print(anan*2)

In [ ]:
a = np.where((the_parameters_0[:,0] < 0.05) & (the_parameters_0[:,0] > 0.025))
aa = a[0]

In [ ]:
print(aa[:100])

phi for CSC 4987.0 ~ 5000 is max, 94~100 is min
theta for CSC 88~90 is max, 5~10 is min

So divide phi by 5000 -> [0,1]
divide theta by 90 -> [0,1]

In [ ]:
print(np.nanmax(the_variables_0[:,12+0]))
print(np.nanmax(the_variables_0[:,12+1]))
print(np.nanmax(the_variables_0[:,12+2]))
print(np.nanmax(the_variables_0[:,12+3]))
print(np.nanmax(the_variables_0[:,12+4]))

In [ ]:
for e in aa[:100]:
    print(the_variables_0[e,0:5])
    print(the_variables_0[e,12+0:12+5])
    print(the_parameters_0[e,0],1/the_parameters_0[e,0])
    print("")

In [ ]:
print(the_parameters_0[:10,0])

In [ ]:
loaded2 = np.load(infile_pileup)

In [ ]:
type(loaded2)

In [ ]:
print(loaded2.keys())

In [ ]:
aux2 = loaded2['aux']

In [ ]:
print(aux2[20000:20010])