In [1]:
import sys
sys.path.append('../test8')

In [2]:
from MK_proc import det_bits

In [3]:
path1 = '/uscms_data/d3/mkim/MKWorkingArea/CMSSW_10_2_0/src/JL/Melrose/P2_CMSSW_10_1_5/src/L1TMuonSimulations/Analyzers/test7/histos_tba.20.npz'

In [4]:
import numpy as np

In [5]:
a = np.load(path1)

In [7]:
det_bits(a, nbits=5, verbose=True)

clip performed
('max: ', 3.0)
('std: ', 2.7769941547845116)
('min: ', -3.0)
[0 1 2 3]
[ 22.15171  -18.459759        nan -13.       -13.         7.
 -24.        25.843662 -16.613783 -13.      ]
[ 3. -3.  4. -3. -3.  3. -3.  3. -3. -3.]


(array([[3.190e+03,       nan, 3.546e+03, ..., 1.000e+00, 1.000e+00,
         1.080e+02],
        [2.865e+03,       nan, 2.622e+03, ..., 7.000e+00, 0.000e+00,
         8.400e+01],
        [      nan, 1.415e+03, 1.455e+03, ..., 4.000e+00, 5.000e+00,
         4.500e+01],
        ...,
        [4.054e+03,       nan, 4.016e+03, ..., 4.000e+00, 1.000e+00,
         1.260e+02],
        [      nan, 3.464e+03, 3.439e+03, ..., 4.000e+00, 5.000e+00,
         1.070e+02],
        [8.360e+02,       nan, 2.960e+02, ..., 8.000e+00, 3.000e+00,
         1.300e+01]], dtype=float32), 2.7769941547845116)