In [1]:
import numpy as np

In [2]:
nums = np.random.randint(low=-40, high=40, size=100)

In [3]:
nums

array([ 22,   6,  10,   0,  -7, -13,  22,   5, -21,  -5, -29,  37,  10,
        -3,   0,   7, -34,  19,  14,  38,  -4,  -9,  25, -23, -14,   0,
        23,   3,  -2,  -9, -32, -29, -15, -32, -23,  11, -30,  -1,  17,
       -37,  -4,  19,  -5, -21, -36,  17, -24,  -8, -22,   5,  32,   4,
         5, -10, -28, -34, -14,  39,  14, -27,  -6,  33,  14,   9,   1,
       -20,   0, -21, -13,  -3,  31,  14,   1,   6,   7,   0,  38,   5,
       -40,  36,  -4,  15,  21,  28,   4,  23, -30, -22, -32,  37, -20,
       -30,  -1, -17, -22,  31, -23,   3,  24,   7])

In [11]:
result

array([ 22,   6,   9,   0,  -6,  -9,  22,   4, -14,  -4, -22,  22,   9,
        -2,   0,   6, -22,  14,  14,  22,  -4,  -9,  22, -22, -14,   0,
        22,   2,  -2,  -9, -22, -22, -14, -22, -22,   9, -22,  -1,  14,
       -22,  -4,  14,  -4, -14, -22,  14, -22,  -6, -22,   4,  22,   4,
         4,  -9, -22, -22, -14,  22,  14, -22,  -6,  22,  14,   9,   1,
       -14,   0, -14,  -9,  -2,  22,  14,   1,   6,   6,   0,  22,   4,
       -22,  22,  -4,  14,  14,  22,   4,  22, -22, -22, -22,  22, -14,
       -22,  -1, -14, -22,  22, -22,   2,  22,   6])

In [4]:
bins = [0,1,2,4,6,9,14,22]

In [12]:
len(bins)-1

7

In [5]:
binsNp = np.asarray(bins)

In [6]:
numsSign = nums.copy()

In [7]:
numsSign[numsSign >= 0] = 1
numsSign[numsSign < 0] = -1

In [8]:
numsAbs = np.abs(nums)

In [9]:
bin_ind = np.digitize(numsAbs,binsNp)

array([8, 5, 6, 1, 5, 6, 8, 4, 7, 4, 8, 8, 6, 3, 1, 5, 8, 7, 7, 8, 4, 6,
       8, 8, 7, 1, 8, 3, 3, 6, 8, 8, 7, 8, 8, 6, 8, 2, 7, 8, 4, 7, 4, 7,
       8, 7, 8, 5, 8, 4, 8, 4, 4, 6, 8, 8, 7, 8, 7, 8, 5, 8, 7, 6, 2, 7,
       1, 7, 6, 3, 8, 7, 2, 5, 5, 1, 8, 4, 8, 8, 4, 7, 7, 8, 4, 8, 8, 8,
       8, 8, 7, 8, 2, 7, 8, 8, 8, 3, 8, 5])

In [10]:
result = binsNp[bin_ind-1]
result = result * numsSign